### ISSUE TITLE
Fundamental : Quantizer scales (FR)

### ISSUE THREAD

**Issue by TheTechnobear** [4ms/metamodule-plugin-examples#8]
in VCV scales are presented as 'presets' for the quantiser and are an important/useful function of the module.

MM has no preset scales.
given the way the encode is used to activate/deactivate notes it is cumbersome to setup a scale.

this is very common use-case when using sequencers in vcv.
we are also not able to copy modules (with settings) on the MM, so if you have multiple sequencers running, you have to manually 'enter the scale' on every quantiser.

**Comment by danngreen** [comment]
Right there's no way to load presets on the MM. 
We could tackle this specific case and add these presets to the QNT module, since I have forked it and made it a custom module anyways. That's fairly easy to implement.

Or a more general thing would be to somehow add the ability to load presets. I suppose they would need to be on the disk in some designated subdir of the plugin's contents and then loaded into RAM when the plugin is loaded. Then something would need to index and keep track of them, and display them as options to the user in the Module View. Reading, parsing, and applying the json is easy enough.

**Comment by danngreen** [comment]
Support for presets in the SDK (and in Quant) was just merged in with PR #12 

We should be merging the support for this in firmware in the next release.
