### ISSUE TITLE
Bogaudio plugins all have "Bogaudio" at the start of their slugs

### ISSUE THREAD

**Issue by gabriel-roth** [4ms/metamodule-plugin-examples#9]
This seems inconsistent — none of the other plugins use this format — and it takes up a lot of space on the MM screens, e.g. if the user hasn't renamed a knob assignment. 

It may be that this is because some of the Bogaudio modules have very generic names, e.g. `LFO` or `VCF`. In that case consider using "Bog" rather than the full "Bogaudio" as a slug, and restricting it to those specific modules (it's probably not needed for e.g. MegaGate.) 

Related note on Bogaudio names: The `8:1` and `1:8` modules are renamed `EightOne` and `OneEight` on the MM. This has led to some confusion (see https://www.modwiggler.com/forum/viewtopic.php?p=4229163#p4229163). Presumably the MM can't handle the colon in module names because it's used as a separator, but if hyphens are allowed then `8-1` and `1-8` might be more intuitive.

**Comment by danngreen** [comment]
The MM uses the unique identifier called the "slug" as defined in the VCV Rack version of the plugin. So these names that you see are just whatever the original author chose to use for the "slug" of the module (MM does not change or create slugs for plugins).

I think the solution is to display the "name" instead of the "slug" since that's what people are used to seeing on VCV Rack. This feature would fall under here:
https://github.com/4ms/metamodule/issues/366

(I'm making a note on that issue to specifically display the plugin name instead of slug)

I'm going to close this, and if you want to track progress you can check that issue.
